name: yolov4-gpu

dependencies:
  - python==3.7
  - pip
  - matplotlib
  - opencv
  - cudnn
  - cudatoolkit==10.1.243
  - shapely
  - pip:
      - tensorflow-gpu==2.3.0rc0
      - opencv-python==4.1.1.26
      - lxml
      - tqdm
      - absl-py
      - easydict
      - pillow
      - m3u8
